name: Keep Render App Alive

on:
  schedule:
    - cron: '*/3 * * * *'  # Every 3 minutes
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render app
        run: curl -m 10 --silent --show-error --fail https://flask-email-app-6zfp.onrender.com/
